language: java

jdk:
  - oraclejdk8

sudo: false

script: 
  - ant run
  - ant jar
  - java -classpath ./dist/SIT213.jar Simulateur -seed 42
  - java -classpath ./dist/SIT213.jar Simulateur -mess "0101011100111"
  - java -classpath ./dist/SIT213.jar Simulateur -mess 12
  - java -classpath ./dist/SIT213.jar Simulateur 

notifications:
  email:
    - sapk@sapk.fr
