language: java
jdk:
- oraclejdk7
- oraclejdk8
sudo: false
script:
- ant -silent run
- ant -silent jar
- ant -silent javadoc
- ant -silent test
- ./simulateur -seed 42
- ./simulateur -mess "0101011100111"
- ./simulateur -mess 12
- ./simulateur
- ./script/test-snr.sh
- ./script/test-charge.sh
- tar cz -f dist/doc.tar.gz -C dist/javadoc .
notifications:
  email:
  - sapk@sapk.fr
deploy:
  provider: releases
  api_key:
    secure: hoLblqP0kIXvogYNVpdlyPDltpN6MScO555pAjfoLNuWw0SLX/4I3MG0O+uEhdNbvTqFMogIRdjE5IGA2ue487fUY8CyVeOGOucEvigitffyWZRLvxAjF9E6w+67AhBo1OFPD2t6O30xU3gDWWYCTFkdn2OnFp/j/mvZ/+OyGPC1dYl+BhjispqdqZlpQpLgIf0VaXe8X8oaQiG/Zenb/W3o6ZU/13vLpSL+Uf8PAhu8la7Xkv2AiQBIFYgOq2Uu/fO1xouVqCjseQ2G4ztttKLvXWEc8hmfZMT1Ln+jgJ0iIcTeZZqUCPwe4kwIq7TlhEpOD92+guJSKBneOrWgVwacIHG0aIVfOUfdX9KY7b4bAK2py4FeIcaBIMyM3eU8d4IVgSwG+h5qJ+zT0WHz0RQVsPtZKLoV6Pq9HPwUiLOOnMzeYtwVvhTOb1gW9+F535CHtioDM6IKVTFzcmsQhVntZi1BxGl5ZIB0xbnrwaA5qBglSZHd0FW+whslkyaFHpth6ZURR+X+ckjcLfPxvl8Wnj6VOd3UL3vDsaOP2t5VCSrEuIpvF8JMiXxktCy+zI51OmZeG+9y5uQPGVTxD2nnHBtLHp2P37HoOVtLdcgS8dQo20E5vjbwHzaSlY7Qo5NxIZsCBXe6YS3JFiTLTXLDAYyRUw1Irli1d0YUakU=
  file: 
  - dist/SIT213.jar
  - dist/doc.tar.gz
  on:
    tags: true

