#!/bin/bash

#TODO améliorer et compiler si necessaire
#if [ ! -f ./dist/SIT213.jar ]; then
#    ant jar
#fi;

ant -quiet compile 

#echo $@
#SIMU_JAVA_OPTIONS="-Xmx6G" 
#ou export SIMU_JAVA_OPTIONS="-Xmx6G" 

java $SIMU_JAVA_OPTIONS -classpath ./build/classes/ Simulateur $@
